# https://balta.io/blog/github-packages-github-actions-distribuindo-contextos-delimitados
name: Build and deploy package

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/wellitontoledo/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Set version number environment variable
      env:
        github_ref: ${{ github.ref }}
      run: |
        version='1.${{ github.run_number }}.${{ github.run_attempt }}'
         echo version=$version
         echo "version=$version" >> $GITHUB_ENV
 
    - name: Build with dotnet
      run: |
        dotnet build "src/BlobHelper/BlobHelper.csproj" --configuration Release -p:Version=${{ env.version }}

    - name: Create the Package
      run: |
        dotnet pack "src/BlobHelper/BlobHelper.csproj" --configuration Release /p:PackageVersion=5.${{ env.version }} #-beta

    - name: Publish the Package
      run: dotnet nuget push "src/BlobHelper/bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/wellitontoledo/index.json --skip-duplicate
       